version: '3.8'
services:
  db_postgres:
    image: postgis/postgis
    container_name: postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres_db_vol:/var/lib/postgresql/data

    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}     
  python-app:
    network_mode: host
    build: ./src
    depends_on:
        - db_postgres

volumes:
    postgres_db_vol: