version: '3.1'

services:

  db:
    container_name: postgresql_db
    image: postgis/postgis
    # automatically restarts the container - Docker daemon on restart or 
    # the container itself is manually restarted
    restart: always 
    networks:
      default:
      outside:
        ipv4_address: 192.168.220.220
    expose:
      - "5432"

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432" 

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - default
      
  python-app:
    network_mode: host
    build: ./python_postgis
    depends_on:
        - db

networks:
  outside:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.220.0/24


    