name: Build & Publish Documentation
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sphinx
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install build dependencies
      run: |
        - python -m pip install -r requirements.txt
    - name: Build Docs
      run: |
        - sphinx-build -b html . _build
    - name: Copy to Github Pages dir
      run: |
        cp -a build/html/. ../docs
    - name: Commit doc changes
      run: |
        git config --global user.name 'Luke Parkinson'
        git config --global user.email 'luke.parkinson@users.noreply.github.com'
        git commit -am "Automated update - Sphinx documentation"
        git push
