# This workflow will install Python dependencies, run tests, lint, and perform static code analysis

name: Run tests

on: push

jobs:
  linting-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: |
          python -m pip install flake8
      - name: Run lint with flake8
        run: |
          flake8 src --show-source --count --statistics --max-line-length=120

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install package dependencies with setup-miniconda@v2
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: digitaltwin
          environment-file: create_new_env_window.yml
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Install pytest
        run: |
          python -m pip install pytest
      - name: Run unit tests
        run: |
          pytest


  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
